### ISSUE TITLE
npm start throws error

### ISSUE THREAD

**Issue by moritzzingg** [signinit/injectable-development-tutorial#1]
I followed the tutorial and installed the packages in the server subfolder via npm install and then started the server with npm run start, but get the following error

>  injectable-development-tutorial-server@1.0.0 start D:\Desktop\injectable-development-tutorial\server
 injectable-server
[4/9/2019 23:59 | ConsoleLogService] Injectable ConsoleLogService Changed State: injectable-preparing-state
[4/9/2019 23:59 | ConsoleLogService] Injectable ConsoleLogService Changed State: injectable-running-state
[4/9/2019 23:59 | ConsoleLogService] Injectable DevelopmentReloadService Changed State: injectable-missing-dependencies-state (ConfigService)
[4/9/2019 23:59 | ConsoleLogService] Injectable ConfigService Changed State: injectable-preparing-state
internal/modules/cjs/loader.js:638
    throw err;
    ^
Error: Cannot find module '@injectable/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Desktop\injectable-development-tutorial\sample-injectable\dist\index.js:16:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! injectable-development-tutorial-server@1.0.0 start: `injectable-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the injectable-development-tutorial-server@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

It looks like the sample-injectable does not have acess to the core dependecies

**Comment by signinit** [comment]
Thanks for writing this issue, I forgot to write that its needed to also run "npm install" in the "/sample-injectable" folder.  
I also found a depedency error so please redownload the tutorial or follow the following steps to update it to the newest version. (any changes from your side will be deleted)
`git reset --hard`
`git pull`
and then do the same as before
in "/server" -> `npm install`
and now also in "/sample-injectable" -> `npm install`

If that fixed your issue feel free to close it.
